/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _5_registro;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author g
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setSize(new Dimension(338, 481));
        PNT.setVisible(false);
        PIA.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) PPTableAlunos.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PP = new javax.swing.JPanel();
        PPLabelRegistroAcademico = new javax.swing.JLabel();
        PPButtonAdicionarTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PPTableTurmas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PPTableAlunos = new javax.swing.JTable();
        PPLabelTurmas = new javax.swing.JLabel();
        PPLabelAlunos = new javax.swing.JLabel();
        PPIncluirAluno = new javax.swing.JButton();
        PPButtonSair = new javax.swing.JButton();
        PNT = new javax.swing.JPanel();
        PNTLabelAdicionarNovaTurma = new javax.swing.JLabel();
        PNTButtonAdicionar = new javax.swing.JButton();
        PNTLabelMateria = new javax.swing.JLabel();
        PNTCampoMateria = new javax.swing.JTextField();
        PNTLabelProfessor = new javax.swing.JLabel();
        PNTCampoProfessor = new javax.swing.JTextField();
        PNTButtonCancelar = new javax.swing.JButton();
        PIA = new javax.swing.JPanel();
        PIALabelIncluirAluno = new javax.swing.JLabel();
        PIALabelNome = new javax.swing.JLabel();
        PIALabelMateria = new javax.swing.JLabel();
        PIACampoNome = new javax.swing.JTextField();
        PIACampoCPF = new javax.swing.JTextField();
        PIAButtonAdicionar = new javax.swing.JButton();
        PIAButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PP.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        PPLabelRegistroAcademico.setText("Registro Acadêmico");

        PPButtonAdicionarTurma.setText("Adicionar Turma");
        PPButtonAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPButtonAdicionarTurmaActionPerformed(evt);
            }
        });

        PPTableTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod.", "Materia", "Professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PPTableTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PPTableTurmasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PPTableTurmas);

        PPTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PPTableAlunos);

        PPLabelTurmas.setText("Turmas");

        PPLabelAlunos.setText("Alunos");

        PPIncluirAluno.setText("Incluir Aluno");
        PPIncluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPIncluirAlunoActionPerformed(evt);
            }
        });

        PPButtonSair.setText("Sair");
        PPButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PPLayout = new javax.swing.GroupLayout(PP);
        PP.setLayout(PPLayout);
        PPLayout.setHorizontalGroup(
            PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PPLayout.createSequentialGroup()
                        .addComponent(PPLabelRegistroAcademico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PPLayout.createSequentialGroup()
                        .addGroup(PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(PPLayout.createSequentialGroup()
                                .addGroup(PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PPLabelTurmas)
                                    .addComponent(PPLabelAlunos))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPLayout.createSequentialGroup()
                                .addGap(0, 184, Short.MAX_VALUE)
                                .addGroup(PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PPButtonAdicionarTurma, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PPIncluirAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PPButtonSair, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        PPLayout.setVerticalGroup(
            PPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PPLabelRegistroAcademico)
                .addGap(18, 18, 18)
                .addComponent(PPButtonAdicionarTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PPLabelTurmas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PPIncluirAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PPLabelAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPButtonSair)
                .addGap(38, 38, 38))
        );

        PNT.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        PNTLabelAdicionarNovaTurma.setText("Adiciona Nova Turma");

        PNTButtonAdicionar.setText("Adicionar");
        PNTButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNTButtonAdicionarActionPerformed(evt);
            }
        });

        PNTLabelMateria.setText("Matéria: ");

        PNTLabelProfessor.setText("Professor: ");

        PNTButtonCancelar.setText("Cancelar");
        PNTButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNTButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNTLayout = new javax.swing.GroupLayout(PNT);
        PNT.setLayout(PNTLayout);
        PNTLayout.setHorizontalGroup(
            PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNTLayout.createSequentialGroup()
                        .addComponent(PNTButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(PNTButtonAdicionar))
                    .addGroup(PNTLayout.createSequentialGroup()
                        .addComponent(PNTLabelAdicionarNovaTurma)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PNTLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PNTLabelMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PNTCampoMateria))
                    .addGroup(PNTLayout.createSequentialGroup()
                        .addComponent(PNTLabelProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(PNTCampoProfessor)))
                .addContainerGap())
        );
        PNTLayout.setVerticalGroup(
            PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNTLabelAdicionarNovaTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNTLabelMateria)
                    .addComponent(PNTCampoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNTLabelProfessor)
                    .addComponent(PNTCampoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNTButtonAdicionar)
                    .addComponent(PNTButtonCancelar))
                .addContainerGap())
        );

        PIA.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        PIALabelIncluirAluno.setText("Incluir Aluno");

        PIALabelNome.setText("Nome:");

        PIALabelMateria.setText("CPF:");

        PIACampoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIACampoCPFActionPerformed(evt);
            }
        });

        PIAButtonAdicionar.setText("Adicionar");
        PIAButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIAButtonAdicionarActionPerformed(evt);
            }
        });

        PIAButtonCancelar.setText("Cancelar");
        PIAButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIAButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PIALayout = new javax.swing.GroupLayout(PIA);
        PIA.setLayout(PIALayout);
        PIALayout.setHorizontalGroup(
            PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PIALayout.createSequentialGroup()
                        .addComponent(PIAButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(PIAButtonAdicionar))
                    .addGroup(PIALayout.createSequentialGroup()
                        .addComponent(PIALabelIncluirAluno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PIALayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PIALabelNome)
                            .addComponent(PIALabelMateria))
                        .addGap(27, 27, 27)
                        .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PIACampoCPF)
                            .addComponent(PIACampoNome))))
                .addContainerGap())
        );
        PIALayout.setVerticalGroup(
            PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PIALabelIncluirAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PIALabelNome)
                    .addComponent(PIACampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PIALabelMateria)
                    .addComponent(PIACampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PIAButtonAdicionar)
                    .addComponent(PIAButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(PP, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PPButtonAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPButtonAdicionarTurmaActionPerformed
        PNT.setLocation(0, 0);
        this.setSize(new Dimension(290, 157));
        PP.setVisible(false); 
        PNT.setVisible(true);
    }//GEN-LAST:event_PPButtonAdicionarTurmaActionPerformed

    private void PNTButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNTButtonAdicionarActionPerformed
        turmas[index] = new Turma(PNTCampoMateria.getText(), new Professor(PNTCampoProfessor.getText()));
        DefaultTableModel model = (DefaultTableModel) PPTableTurmas.getModel();
        model.addRow(new Object[]{index, turmas[index].getMateria(), turmas[index].getProfessor().getNome()});
        index++;
        this.setSize(new Dimension(330, 473));
        PNTCampoMateria.setText("");
        PNTCampoProfessor.setText("");
        PNT.setVisible(false);
        PP.setVisible(true); 
    }//GEN-LAST:event_PNTButtonAdicionarActionPerformed

    private void PIAButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIAButtonAdicionarActionPerformed
        this.setSize(new Dimension(330, 473));
        Aluno aluno = new Aluno(PIACampoNome.getText(), PIACampoCPF.getText());
        turmas[selectedIndex].incluirAluno(aluno);
        PPTableTurmas.clearSelection();
        PIACampoCPF.setText("");
        PIACampoNome.setText("");
        PIA.setVisible(false);
        PP.setVisible(true);
    }//GEN-LAST:event_PIAButtonAdicionarActionPerformed

    private void PPIncluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPIncluirAlunoActionPerformed
        Integer row = PPTableTurmas.getSelectedRow();
        selectedIndex = (Integer) PPTableTurmas.getValueAt(row, 0);
        if (turmas[selectedIndex] != null) {
            PIA.setLocation(0, 0);
            this.setSize(new Dimension(290, 164));
            PP.setVisible(false);
            PIA.setVisible(true);
        }
    }//GEN-LAST:event_PPIncluirAlunoActionPerformed

    private void PNTButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNTButtonCancelarActionPerformed
        this.setSize(new Dimension(330, 473));
        PNTCampoMateria.setText("");
        PNTCampoProfessor.setText("");
        PNT.setVisible(false);
        PP.setVisible(true);
    }//GEN-LAST:event_PNTButtonCancelarActionPerformed

    private void PPButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_PPButtonSairActionPerformed

    private void PIAButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIAButtonCancelarActionPerformed
        this.setSize(new Dimension(330, 473));
        PIACampoCPF.setText("");
        PIACampoNome.setText("");
        PIA.setVisible(false);
        PP.setVisible(true);
    }//GEN-LAST:event_PIAButtonCancelarActionPerformed

    private void PIACampoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIACampoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIACampoCPFActionPerformed

    private void PPTableTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPTableTurmasMouseClicked
        DefaultTableModel model = (DefaultTableModel) PPTableAlunos.getModel();
        model.setRowCount(0);
        Integer row = PPTableTurmas.getSelectedRow();
        selectedIndex = (Integer) PPTableTurmas.getValueAt(row, 0);
        for (Integer i = 0; i < turmas[selectedIndex].getAlunos().length; i++) {
            model.addRow(new Object[]{turmas[selectedIndex].getAlunos()[i].getCPF(), turmas[selectedIndex].getAlunos()[i].getNome()});
        }
    }//GEN-LAST:event_PPTableTurmasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    private Integer index = 1;
    private Turma[] turmas = new Turma[50];
    private Integer selectedIndex;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PIA;
    private javax.swing.JButton PIAButtonAdicionar;
    private javax.swing.JButton PIAButtonCancelar;
    private javax.swing.JTextField PIACampoCPF;
    private javax.swing.JTextField PIACampoNome;
    private javax.swing.JLabel PIALabelIncluirAluno;
    private javax.swing.JLabel PIALabelMateria;
    private javax.swing.JLabel PIALabelNome;
    private javax.swing.JPanel PNT;
    private javax.swing.JButton PNTButtonAdicionar;
    private javax.swing.JButton PNTButtonCancelar;
    private javax.swing.JTextField PNTCampoMateria;
    private javax.swing.JTextField PNTCampoProfessor;
    private javax.swing.JLabel PNTLabelAdicionarNovaTurma;
    private javax.swing.JLabel PNTLabelMateria;
    private javax.swing.JLabel PNTLabelProfessor;
    private javax.swing.JPanel PP;
    private javax.swing.JButton PPButtonAdicionarTurma;
    private javax.swing.JButton PPButtonSair;
    private javax.swing.JButton PPIncluirAluno;
    private javax.swing.JLabel PPLabelAlunos;
    private javax.swing.JLabel PPLabelRegistroAcademico;
    private javax.swing.JLabel PPLabelTurmas;
    private javax.swing.JTable PPTableAlunos;
    private javax.swing.JTable PPTableTurmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
